version: 2
updates:
  - package-ecosystem: maven
    directory: "/spring-security-sso-auth-server"
    schedule:
      interval: daily
      time: ’05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  
  - package-ecosystem: maven
    directory: "/spring-security-sso-ui"
    schedule:
      interval: daily
      time: ’05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
